#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Standard

# ROS
import rospy

# AIRA
from robonomics_msgs.msg import Demand, Result
from temperature_sensor_demo.get_temperature import get_temperature

class WorkerNode:
    def __init__(self):
        rospy.init_node('worker')
        rospy.loginfo('Launching worker node...')

        rospy.Subscriber('/liability/infochan/incoming/demand', Demand, self.on_incoming_demand)

        self.result_publish = rospy.Publisher('/liability/infochan/eth/signing/result', Result, queue_size=128)

        self.NO_SENSOR = bool(rospy.get_param("~no_sensor"))
        rospy.loginfo("No sensor: {}".format(self.NO_SENSOR))

        rospy.loginfo('Worker node launched.')

    def on_incoming_demand(self, msg: Demand):
        rospy.loginfo('Incoming demand %s...', str(msg))
        if (msg.model.multihash == rospy.get_param('~model') and msg.sender.address == rospy.get_param('~account')):
            self.send_result(msg)

    def send_result(self, msg: Demand):
        rospy.loginfo('Starting process...')

        res = Result()
        res.liability = msg.sender
        res.result = get_temperature(self.NO_SENSOR)
        res.success = True

        rospy.loginfo(res)

        self.result_publish.publish(res)

    def spin(self):
        rospy.spin()

if __name__ == '__main__':
    WorkerNode().spin()

